---
- name: test command delegate to
  become: yes
  hosts: virtual

  tasks:
  - name: Create file 1
    copy:
      dest: /home/file1.txt
      content: |
        Here is some text in file1 by {{ OWNER }}
    delegate_to: linux3

  - name: Create file 2
    copy:
      dest: /home/file2.txt
      content: |
        Here is some text in file2 by {{ OWNER }}

