---
- block:
    - name: Start download updates
      yum: 
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status

    - name: Remove packages not needed anymore
      yum:
        autoremove: yes

    - name: Reboot when packages were updated
      reboot:
      when: yum_update_status.changed

  when: ansible_os_family == "RedHat"

- block:
    - name: Start download updates
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
      register: apt_update_status

    - name: Remove packages not needed anymore
      apt:
        autoremove: yes

    - name: Reboot when packages were updated
      reboot:
        post_reboot_delay: 60
      when: apt_update_status.changed
  when: ansible_os_family == "Debian"
